$(function(){
    $(".conbox").mousedown(function(e){
        e.preventDefault();
    }).mouseover(function(e){
        e.preventDefault();
    })
    var num=0;
    var clienth=document.documentElement.clientHeight;
    var flag=true;
    touch.on("body","swipeup",".conbox",function(){
        if(!flag){
            return;
        }
        num++;
        if(num>=$(".con").length){
            num=$(".con").length-1;
            return;
        }
        flag=false;
        if(num*clienth>=clienth){
            $(".lianxi1").animate({opacity:0},800);
        }else{
            $(".lianxi1").animate({opacity:1},800);
        }
        $(".conbox").css({
            marginTop:-num*clienth
        })
    })
    touch.on("body","swipedown",".conbox",function(){
        if(!flag){
            return;
        }
        num--;
        if(num<0){
            num=0;
            return;
        }
        flag=false;
        if(num*clienth>=clienth){
            $(".lianxi1").animate({opacity:0},800);
        }else{
            $(".lianxi1").animate({opacity:1},800);
        }
        $(".conbox").css({
            marginTop:-num*clienth
        })
    })
    $(".conbox")[0].addEventListener("webkitTransitionEnd",function(){
        flag=true;
    })
    $(".conbox")[0].addEventListener("msTransitionEnd",function(){
        flag=true;
    })
    $(".conbox")[0].addEventListener("mozTransitionEnd",function(){
        flag=true;
    })
    $(".conbox")[0].addEventListener("oTransitionEnd",function(){
        flag=true;
    })
})